services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  FGTCLB\AcademicPersonsEdit\:
    resource: '../Classes/*'

  FGTCLB\AcademicPersonsEdit\EventListener\GenerateSlugForProfile:
    tags:
      - name: event.listener
        identifier: generateSlugForProfile
        event: FGTCLB\AcademicPersons\Event\AfterProfileUpdateEvent

  FGTCLB\AcademicPersonsEdit\EventListener\SyncChangesToTranslations:
    tags:
      - name: 'event.listener'
        identifier: syncChangesToTranslations
        event: 'FGTCLB\AcademicPersons\Event\AfterProfileUpdateEvent'
