name: tests core 11
# disabled, but kept to have the ability to create badges later after merging to main.
on:
  workflow_dispatch:

jobs:
  code-quality:
    name: "code quality with core v11"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-version: [ '8.0' ]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
